blogger_page:
    resource: "@BloggerBlogBundle/Controller/PageController.php"
    type:     annotation

blogger_blog:
    resource: "@BloggerBlogBundle/Controller/BlogController.php"
    type:     annotation

blogger_comment:
    resource: "@BloggerBlogBundle/Controller/CommentController.php"
    type:     annotation

#blogger_blog:
#    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
